spring:
  datasource:
    password: '*****'
    url: jdbc:mysql://localhost:3306/vjanadri
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
